#!/bin/bash

# buildcaddy - Build caddy with plugins from source
# Required: go coreutils(cd) sed $EDITOR/nano mkplugins[script]
# Installing go:
# - Download: wget https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz
# - Install: sudo tar -C /usr/local -xf o1.9.linux-amd64.tar.gz
# - Add to PATH: export PATH=$PATH:/usr/local/go/bin # in /etc/profile

caddy_loc=/usr/local/bin

Try(){
	echo "Trying '$@'"
	"$@" && return
	echo "ERROR: command failed, code: $?"
	read -p "Enter to continue, Ctrl-C to exit"
	return 1
}

[[ $GOPATH ]] && gopath=${GOPATH%%:*} || gopath=$HOME/go
pwd=$PWD
Try mkdir -p "$gopath/src"
Try cd "$gopath/src"
Try go get -u github.com/mholt/caddy
Try go get -u github.com/caddyserver/builds
Try cd "$gopath/src/github.com/mholt/caddy"
# Generate current plugins list
Try bash "$pwd/mkplugins" "$gopath/src/github.com/mholt/caddy/caddy/caddymain/plugins.go"
# Uncomment the desired plugins
editor=${EDITOR:-nano}
"$editor" "$gopath/src/github.com/mholt/caddy/caddy/caddymain/plugins.go"
[[ -f modcaddy ]] && Try bash modcaddy
Try go get -u -v -f ...
Try go run build.go goos=linux
Try mkdir -p "$caddy_loc"
Try sudo /bin/cp -f caddy/caddy "$caddy_loc/"

exit 0
