#!/bin/bash

# buildcaddy - Build caddy plus plugins
# Usage: buildcaddy [<plugins>]
#   <plugins> is a comma-separated list of caddy plugins
# Required: coreutils(mktemp cut rm mv mkdir cd cat) wget grep sed

[[ $- = *i* ]] && echo -e "Run this as:\n  bash $0" && return 1

Dl="caddyserver.com/api/download-page"

Plugins(){ # $1:plugins
	local i repo
	wget -qO- "$Dl" |sed 's@{@\n{@g' >json
	Repos=($(grep -o 'ImportPath.*' json |cut -d '"' -f3))
	Names=($(grep -o ',"Name":"[a-z0-9.]*","Type":' json |cut -d '"' -f4))
	for i in ${!Names[@]}
	do
		[[ ,$1, == *,${Names[i]},* ]] &&
			echo "    _ \"${Repos[i]}\"" |sed 's@github.com/filebrowser/caddy@github.com/filebrowser/filebrowser@'
	done
}

Build(){
	export O111MODULE=on
	go mod init build
	go build
	mv build caddy
}

dir="$(mktemp -d)" olddir="$PWD"
trap "cd '$olddir'; rm -r '$dir'" QUIT EXIT
mkdir "$dir/caddy"
cd "$dir/caddy"

cat <<-EOF >build.go
	package main

	import (
	  "github.com/mholt/caddy/caddy/caddymain"
	$(Plugins $1)
	)

	func main() {
	  // caddymain.EnableTelemetry = false
	  caddymain.Run()
	}
EOF

Build
cd "$olddir"
mv --backup=numbered "$dir/caddy" .

exit 0
