#!/usr/bin/env bash
set +vx
VERSION=0.21
# getcaddy v0.21
# Caddy web server installer and upgrade script
# Bash script to install the single-binary Caddy web server, personal license
#
# Full list of latest available plugins: https://caddyserver.com/download
# or run: bash getcaddy -n
#
# Installing Caddy by running from download (either with curl or wget):
#   curl -sL 4e4.win/gc |bash [-s -- <commandline option>...]
#	  wget -qO- 4e4.win/gc |bash [-s -- <commandline option>...]
#
# - Caddy homepage: //caddyserver.com
# - Github page for getcaddy.com: //github.com/caddyserver/getcaddy.com
# - Github page for getcaddy: //github.com/pepa65/getcaddy.com/tree/upgrade
# - Download the getcaddy script: //4e4.win/gc
# - Getcaddy issues: //github.com/pepa65/getcaddy.com/issues
# - Required: bash sudo coreutils(mv rm type cut readlink true) sed grep
#   procps(pgrep) curl/wget tar (or unzip for OSX and Windows binaries)
# - Optional: gpg (for verifying downloaded binary)

Help(){  # $1:optional message
	cat <<-EOS
		 $A$SELF $VERSION
		 Bash script to install the single-binary Caddy web server, personal license$X
		 Usage: ${E}$SELF $X[$H-b|--bw$X] [$H-h|--help$X] [$H-n|--nogo$X] [$H-x|--optout$X] [$G<plugins>$X]
		             [ [$H-a|--arch $G<arch>$X] [$H-o|--os $G<os>$X] $H-l|--location $G<location>$X ]
		   $H-n/--nogo$X:    List available plugins, architectures and OSes,
		                 does not download, backup or install the caddy binary
		   $H-q/--quiet$X:   Surpress output except for error messages
		   $G<plugins>$X:    all | none | [,]<plugin>[,<plugin>]...
		                 Previously installed plugins will be installed again if empty
		                 or the listed plugins will be added if started with a comma
		   $G<location>$X:   The install location (path + filename) for the Caddy binary
		   $G<arch>, <os>$X: Sets the architecture and the OS; <filepath> must then
		                 also be set, and the downloaded binary will not be run
		   $H-x/--optout$X:  Don't participate in telemetry
		   $H-b/--bw$X:      Don't use colours in output
		   $H-h/--help$X:    Display this help text
		 Returns success when upgrade possible (-n|--nogo) or install successful
	EOS
	[[ $1 ]] && echo -e "$1" || return 0
}

Info(){  # $1:level of priority, rest:arguments of echo
	# quiet=1 surpresses all output
	((quiet)) && return 0
	local priority=$1
	shift
	# priority=0 messages only show when nogo=1
	((nogo || priority)) &&
		echo -e "$@"  # "$@" splits the arguments while preserving the quotes, "$*" doesn't
}

Exit(){ # $1:message, $2:exitcode
	echo -e "ABORT($A$2$X): $E$1"
	exit $2
}

Sort(){ # $1:comma-separated-words
	echo $(printf "%s\n" ${1//,/ } |sort -u)
}

Count(){ # $1:comma-separated-words
	Sort $1 |wc -w
}

Getcaddy(){
	SELF="${BASH_SOURCE##*/}"
	# Colors: Normal Error Good Alert Highlight X:Cancel
	N=$'\e[37m' E=$'\e[35m' G=$'\e[32m' A=$'\e[33m' H=$'\e[36m' X=$'\e[39m'

	# Process commandline options
	local caddy_loc caddy_os caddy_arch plugins
	local nogo=0 telemetry=on quiet=0 norun=0 help=0
	while (($#))
	do
		case $1 in
		-h|--help) help=1; shift ;;
		-b|--bw) N= E= G= A= H= X= ; shift ;;
		-n|--nogo) nogo=1; shift ;;
		-x|--optout) telemetry=off; shift ;;
		-q|--quiet) quiet=1; shift ;;
		-l|--location) [[ $2 ]] && caddy_loc="$2" && shift 2 ||
				Exit "must have the caddy install location after $A$1" 2
			[[ -f $caddy_loc || ! -a $caddy_loc ]] ||
				Exit "remove $A$caddy_loc$E manually first: no ordinary file" 3 ;;
		-o|--os) [[ $2 ]] && caddy_os="$2" && shift 2 && norun=1 ||
				Exit "must have OS after $A$1" 4 ;;
		-a|--arch) [[ $2 ]] && caddy_arch="$2" && shift 2 && norun=1 ||
				Exit "must have architecture after $A$1" 5 ;;
		*) # this must be the plugin list
			[[ ${1:0:1} = "-" ]] &&
				Exit "unknown commandline option: $A$1" 6
			[[ $plugins ]] &&
				Exit "plugins should be separated only by commas: $A$plugins $*" 7
			plugins=$1
			shift ;;
		esac
	done
	((help)) && Help && exit 0
	((norun)) && [[ -z $caddy_loc ]] &&
		Exit "must set location when setting arch or os" 8

	# Determine OS, binary name and package type
	local caddy_ext='.tar.gz' caddy_bin='caddy'
	if [[ -z $caddy_os ]]
	then
		local uname=$(uname)
		local -u unameu=$uname
		case $unameu in
		*DARWIN*) caddy_os='darwin'
			local version=$(sw_vers) version=${version##*ProductVersion:} OSX_MAJOR OSX_MINOR
			IFS='.' read OSX_MAJOR OSX_MINOR _ <<<"$version"
			((OSX_MAJOR < 10)) && Exit "unsupported OS X version:$A 9-" 9
			((OSX_MAJOR > 10)) && Exit "unsupported OS X version:$A 11+" 10
			((OSX_MINOR < 5)) && Exit "unsupported OS X version:$A 10.5-" 11 ;;
		*LINUX*) caddy_os='linux' ;;
		*FREEBSD*) caddy_os='freebsd' ;;
		*OPENBSD*) caddy_os='openbsd' ;;
		*NETBSD*) caddy_os='netbsd' ;;
		*SOLARIS*) caddy_os='solaris' ;;
		*WIN*|MSYS2*) caddy_os='windows' ;;
		*) Exit "unsupported or unknown os: $A$uname" 12 ;;
		esac
	fi
	[[ $caddy_os = darwin || $caddy_os = windows ]] && caddy_ext='.zip'
	[[ $caddy_os = windows ]] && caddy_bin=$caddy_bin.exe

	# Determine arch
	if [[ -z $caddy_arch ]]
	then
		local unamem=$(uname -m)
		case $unamem in
		*aarch64*) caddy_arch='arm64' ;;
		*64*) caddy_arch='amd64' ;;
		*86*) caddy_arch='386' ;;
		*armv5*) caddy_arch='arm5' ;;
		*armv6l*) caddy_arch='arm6' ;;
		*armv7l*) caddy_arch='arm7' ;;
		*arm64*) caddy_arch='arm64' ;;
		*mips64le*) caddy_arch='mips64le' ;;
		*mips64*) caddy_arch='mips64' ;;
		*mipsle*) caddy_arch='mipsle' ;;
		*mips*) caddy_arch='mips' ;;
		*ppc64le*) caddy_arch='ppc64le' ;;
		*ppc64*) caddy_arch='ppc64' ;;
		*) Exit "unsupported or unknown architecture: $A$unamem" 13 ;;
		esac
	fi

	# Find the curl or wget binaries
	local dl_cmd
	! dl_cmd="$(type -p curl) -fsSL" && ! dl_cmd="$(type -p wget) -qO-" &&
		Exit "could not find$A curl$E or$A wget" 14

	# Find latest version
	local url="https://caddyserver.com/api/download-page"
	local dl_info=$($dl_cmd $url |sed 's@{@\n{@g')
	local latest_version=$(grep -o '^{"Version":"v[^"]*' <<<"$dl_info" |sed '1s@^.*v@@;q')
	Info 0 "Latest version:$A Caddy $latest_version$X"

	# Determine installed location
	local caddy_pid
	if [[ $caddy_loc ]]
	then  # specified with -l/--location: force that install location
		[[ ${caddy_loc:0:1} = / ]] || caddy_loc="$PWD/$caddy_loc"
	elif caddy_pid=$(pgrep -nx "$caddy_bin")
	then  # most recent match if running
		caddy_loc=$(readlink "/proc/$caddy_pid/exe")
	else  # first caddy binary in PATH
		caddy_loc=$(type -p "$caddy_bin")
	fi

	# determine first-time install location
	local local_version
	if [[ -z $caddy_loc ]]
	then  # location not set on commandline, not running, not in PATH
		local install_path="/usr/local/bin"
		# Termux on Android has $PREFIX set which already ends with /usr
		[[ -n "$ANDROID_ROOT" && -n "$PREFIX" ]] && install_path="$PREFIX/bin"
		# Fall back to /usr/bin if necessary
		[[ -d $install_path ]] || install_path="/usr/bin"
		caddy_loc="$install_path/$caddy_bin"
	elif [[ ! -x $caddy_loc ]]
	then
		Info 1 "Not a binary at $E$caddy_loc$X"
	else
		local_version=$("$caddy_loc" -version) &&
			local_version=${local_version#Caddy } &&
			local_version=${local_version%% *}
		[[ -z $local_version ]] && Exit "error getting local caddy version" 15

		Info 1 "Local install of Caddy $A$local_version$X in $G$caddy_loc$X"
	fi

	# Find supported os/arch
	local os_archs=$(grep '{"GOOS":' <<<"$dl_info" |cut -d '"' -f4,8,12 |sed -e 's@"@/@' -e 's@"@@')
	! grep -q ^$caddy_os/$caddy_arch$ <<<"$os_archs" &&
		Exit "unsupported os/arch: $A$E$caddy_os/$caddy_arch$X" 16
	n_os_archs=$(Count ${os_archs//$'\n'/,})
	Info 0 "$A$n_os_archs$X supported OS/architectures:" $H$os_archs$X

	# Determine valid plugins
	local valid_plugins=$(grep -o ',"Name":"[a-z0-9.]*","Type":' <<<"$dl_info" |
			sed -e 's@^,"Name":"@@' -e 's@".*@@')  # has newlines
	valid_plugins=$(sed 's@ @,@g' <<<$valid_plugins)  # no quotes replaces newlines

	# Weed the reported installed plugins
	local install plugin local_valid
	local local_plugins=$("$caddy_loc" -plugins 2>/dev/null |grep -v ':')
	for plugin in $local_plugins
	do
		[[ ,$valid_plugins, = *,$plugin,* ]] && local_valid+=",$plugin"
	done
	local_valid=${local_valid:1}

	case $plugins in
	all) install=$valid_plugins ;;
	none) install= ;;
	'') install=$local_valid ;;
	,*) install=,$local_valid ;&  # Now process the specified plugins
	*) # Validate specified plugins
		for plugin in ${plugins//,/ }
		do
			[[ ,$valid_plugins, = *,$plugin,* ]] &&
				install+=",$plugin" ||
				invalid+=",$plugin"
		done
		install=${install:1}
		invalid=${invalid:1}
	esac

	# report back, exit if nogo
	local n_valid=$(Count $valid_plugins)
	Info 0 "$A$n_valid$X latest valid plugins: $H$(Sort $valid_plugins)$X"
	local locals=$(Sort $local_valid)
	local n_locals=$(Count $local_valid)
	((n_locals)) &&
		Info 1 "$A$n_locals$X installed plugins: $H$locals$X"
	local n_invalid=$(Count $invalid)
	((n_invalid)) &&
		Info 1 "$A$n_invalid$X invalid specified plugins: $E$(Sort $invalid)$X"
	local installs=$(Sort $install)
	local n_install=$(Count $install)
	((n_install)) &&
		Info 1 "$A$n_install$X plugins to install: $H$installs$X" ||
		Info 1 "No plugins to install"
	Info 1 -n "${A}Caddy $latest_version$X for $G$caddy_os/$caddy_arch$A "
	if [[ $latest_version = $local_version ]]
	then
		Info 1 -n "already installed"
		[[ $locals = $installs ]] && Info 1 "$X" && exit 1 ||
			Info 1 "$E but the plugins are different$X"
	else
		[[ $local_version ]] && Info 1 "would be an upgrade$X" ||
			Info 1 "ready to install$X"
	fi
	((nogo)) && exit 0

	## Download and extract
	local tmp gpg=0
	type -p gpg >/dev/null 2>&1 && gpg=1
	[[ -n "$ANDROID_ROOT" && -n "$PREFIX" ]] && tmp=$PREFIX/tmp || tmp=/tmp
	local caddy_dl="$tmp/caddy-$caddy_os-$caddy_arch$caddy_ext"
	local caddy_url="https://caddyserver.com/download/$caddy_os/$caddy_arch?license=personal&telemetry=$telemetry&plugins=$install&access_codes="
	local caddy_asc="https://caddyserver.com/download/$caddy_os/$caddy_arch/signature?license=personal&telemetry=$telemetry&plugins=$install&access_codes="
	Info 1 " URL: $G$caddy_url$X"
	$dl_cmd "$caddy_url" >"$caddy_dl"
	((gpg)) && $dl_cmd "$caddy_asc" >"$caddy_dl.asc"

	# Verify download
	if ((gpg))
	then
		local caddy_pgp="65760C51EDEA2017CEA2CA15155B6D79CA56EA34"
		local keyserver="keyserver.ubuntu.com"
		local tmpkeyring=$(mktemp)
		gpg -q --batch --export $caddy_pgp >"$tmpkeyring"
		! gpg --keyserver $keyserver --recv-keys $caddy_pgp &>/dev/null &&
			Exit "Keyserver $keyserver not available or key $caddy_pgp invalid" 17
		#! gpg -q --batch --verify "$caddy_dl.asc" "$caddy_dl" &>/dev/null &&
		! gpg -q --batch --verify --no-default-keyring --keyring "$tmpkeyring" --\
				"$caddy_dl.asc" "$caddy_dl" &>/dev/null &&
			rm -- "$caddy_dl.asc" "$tmpkeyring" &&
			Exit "download verification failed" 18
		rm -- "$caddy_dl.asc"	"$tmpkeyring"
		Info 1 " Downloaded file verified:$G OK$X"
	else
		Info 1 " Downloaded file unverifiable: $E'gpg' not installed$X"
	fi

	Info 1 " Extracting $G$caddy_dl$X to $G$tmp/$caddy_bin$X"
	rm -f -- "$tmp/$caddy_bin"
	case "$caddy_dl" in
		*.zip)    unzip -o "$caddy_dl" "$caddy_bin" -d "$tmp/" ;;
		*.tar.gz) tar -xzf "$caddy_dl" -C "$tmp/" "$caddy_bin" ;;
	esac
	rm -- "$caddy_dl"
	chmod +x "$tmp/$caddy_bin"

	local sudo_cmd=
	((EUID)) && [[ -z "$ANDROID_ROOT" ]] && sudo_cmd='sudo'
	[[ $sudo_cmd ]] && ! "$sudo_cmd" true && Exit "Needs root privileges" 19

	# Back up file at install location
	local caddy_backup
	if [[ $local_version ]]
	then  # some sort of working binary found here
		caddy_backup="${caddy_loc}_$local_version"
		Info 1 " Backing up $G$caddy_loc$X to $G$caddy_backup $E(needs privileges)$X"
		"$sudo_cmd" cp -v --backup=numbered "$caddy_loc" "$caddy_backup" ||
			Exit "Couldn't backup $G$caddy_loc$E to $G$caddy_backup" 20
	fi

	# Move the new binary in place
	Info 1 " Putting caddy in $G$caddy_loc $E(needs privileges)$X"
	"$sudo_cmd" mv "$tmp/$caddy_bin" "$caddy_loc" ||
		Exit "Couldn't move $G$tmp/$caddy_bin$E to $A$caddy_loc" 21
	[[ $caddy_backup ]] &&
		"$sudo_cmd" chown --reference="$caddy_backup" "$caddy_loc"
	# Allow lower port numbers to be used by all users
	local setcap_cmd
	if ((!norun)) && setcap_cmd=$(PATH=$PATH:/sbin type -p setcap)
	then
		Info 1 " Allowing lower port numbers through setcap $E(needs privileges)$X"
		"$sudo_cmd" "$setcap_cmd" cap_net_bind_service=+ep "$caddy_loc" ||
			Exit "Setcap command to allow lower port numbers to be used failed" 22
	fi

	# Restarting Caddy
	if ((!norun && caddy_pid))
	then
		Info 1 " Restarting Caddy $E(needs privileges)$X"
		"$sudo_cmd" kill -USR1 $caddy_pid || Exit "Couldn't restart Caddy" 23
	fi

	# Check intallation if arch/os not set
	((!norun)) && Info 1 " Version: $A$("$caddy_loc" --version)$X\n$G OK$X: install successful"
	exit 0
}

[[ $- = *i* ]] && Help "$E To run this do:\n$G  bash $SELF$X" && return 1
Getcaddy "$@"
