#!/usr/bin/env bash

# Install getcaddy: the Caddy web server installer and upgrade script
# - Gitlab page: //gitlab.com/pepa65/getcaddy.com/tree/upgrade
# - Download this igetcaddy script: //4e4.win/ig
# - Report issues: //gitlab.com/pepa65/getcaddy.com/issues
# - Required: bash, sudo, curl/wget
# Usage: wget -qO- 4e4.win/ig |bash [-s <desired location>]
#        Where <desired location is the path+filename for the getcaddy script

Igetcaddy(){
	location=/usr/local/bin/getcaddy
	[[ $1 ]] && location=$1
	getcaddy=$(wget -qO- 4e4.win/gc)
	echo "Installing 'getcaddy' (requires privileges)"
	echo "$getcaddy" |sudo tee "$location" >/dev/null &&
		sudo chmod +x "$location" &&
		echo "Installed 'getcaddy' in $location" ||
		echo "ERROR: install not successfull"
}

[[ $- = *i* ]] && echo -e "Run as:\n   bash $0" && return 1
Igetcaddy "$@"
exit 0
